{
 "title": "anotter-room-sensor",
 "description": "Dashboard for the anotter-room-sensor board https://github.com/Jana-Marie/anotter-sensor-hub",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "VOCx",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sen055_voc_index" }
   ]
  },
  {
   "title": "NOx",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sen055_nox_index", "legendFormat": "NOx" }
   ]
  },
  {
   "title": "PM 1, 2.5, 4 & 10",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "μg/m3" } },
   "targets": [
    { "expr": "sen055_mass_concentration", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sen055_nox_index OR sen055_voc_index)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sen055_mass_concentration", "legendFormat": "{{size}}" },
    { "expr": "sen055_voc_index", "legendFormat": "vocx" },
    { "expr": "sen055_nox_index", "legendFormat": "nox" },
    { "expr": "sen055_ambient_temperature", "legendFormat": "temperature" },
    { "expr": "sen055_ambient_humidity", "legendFormat": "humidity" }
   ]
  },
  {
   "title": "Temperature & Humidity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "sen055_ambient_temperature", "legendFormat": "Temperature" },
    { "expr": "sen055_ambient_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "VOCx",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "voc_index", "legendFormat": "VOCx" }
   ]
  },
  {
   "title": "NOx",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nox_index", "legendFormat": "NOx" }
   ]
  }
 ]
}